test

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -29,9 +29,10 @@ jobs:
 
     - name: Build and Test with Maven
       run: mvn clean test
+      continue-on-error: true
 
     - name: Generate Allure Report
-      run: mvn allure:report
+      run: mvn allure:report || echo "Allure report generation failed"
       continue-on-error: true
 
     - name: Upload Allure Report as Artifact
